version: '3'

services:
  duber_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duber_db
    ports:
      - "6432:5432"